// <auto-generated />
using System;
using HRM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HrmDbContext))]
    [Migration("20260922071845_AddLaborContract")]
    partial class AddLaborContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRM.Domain.Entities.HrBaseSalaryRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveDate")
                        .IsUnique();

                    b.ToTable("HrBaseSalaryRate", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date");

                    b.Property<int>("OrganizationalUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("JobTitleId");

                    b.HasIndex("OrganizationalUnitId");

                    b.ToTable("HrEmployee", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrEmployeeSalary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SalaryDecisionId")
                        .HasColumnType("int");

                    b.Property<int>("SalaryGradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalaryDecisionId");

                    b.HasIndex("SalaryGradeId");

                    b.HasIndex("EmployeeId", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("HrEmployeeSalary", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrJobTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HrJobTitle", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrLaborContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ContractSalaryAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("SalaryNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContractNumber")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("HrLaborContract_index_one_active_per_employee")
                        .HasFilter("[Status] = 'ACTIVE'");

                    b.ToTable("HrLaborContract", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrOrganizationalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique()
                        .HasFilter("[ParentId] IS NOT NULL");

                    b.ToTable("HrOrganizationalUnit", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("ReviewPeriodId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DecisionNumber")
                        .IsUnique();

                    b.HasIndex("ReviewPeriodId")
                        .IsUnique()
                        .HasDatabaseName("HrSalaryDecision_index_noncancelled_period")
                        .HasFilter("[Status] <> 'CANCELLED'");

                    b.ToTable("HrSalaryDecision", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryDecisionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaselineCoefficient")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("BaselineSalaryGradeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("NewCoefficient")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("NewSalaryGradeId")
                        .HasColumnType("int");

                    b.Property<int>("SalaryDecisionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaselineSalaryGradeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("NewSalaryGradeId");

                    b.HasIndex("SalaryDecisionId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("HrSalaryDecisionDetail", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradeNumber")
                        .HasColumnType("int");

                    b.Property<int>("SalaryScaleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SalaryScaleId", "GradeNumber")
                        .IsUnique();

                    b.ToTable("HrSalaryGrade", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryGradeCoefficient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("SalaryGradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalaryGradeId", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("HrSalaryGradeCoefficient", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryReviewEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentCoefficient")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CurrentSalaryGradeId")
                        .HasColumnType("int");

                    b.Property<bool>("Eligible")
                        .HasColumnType("bit");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("IneligibleReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("ProposedCoefficient")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ProposedSalaryGradeId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReviewPeriodId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSalaryGradeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProposedSalaryGradeId");

                    b.HasIndex("ReviewPeriodId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("HrSalaryReviewEmployee", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryReviewPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HrSalaryReviewPeriod", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HrSalaryScale", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrEmployee", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrJobTitle", "JobTitle")
                        .WithMany("Employees")
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrOrganizationalUnit", "OrganizationalUnit")
                        .WithMany("Employees")
                        .HasForeignKey("OrganizationalUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobTitle");

                    b.Navigation("OrganizationalUnit");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrEmployeeSalary", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrEmployee", "Employee")
                        .WithMany("Salaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrSalaryDecision", "SalaryDecision")
                        .WithMany()
                        .HasForeignKey("SalaryDecisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.Domain.Entities.HrSalaryGrade", "SalaryGrade")
                        .WithMany()
                        .HasForeignKey("SalaryGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("SalaryDecision");

                    b.Navigation("SalaryGrade");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrLaborContract", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrEmployee", "Employee")
                        .WithMany("Contracts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrOrganizationalUnit", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrOrganizationalUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryDecision", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrSalaryReviewPeriod", "ReviewPeriod")
                        .WithMany("Decisions")
                        .HasForeignKey("ReviewPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReviewPeriod");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryDecisionDetail", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrSalaryGrade", "BaselineSalaryGrade")
                        .WithMany()
                        .HasForeignKey("BaselineSalaryGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrEmployee", "Employee")
                        .WithMany("DecisionDetails")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrSalaryGrade", "NewSalaryGrade")
                        .WithMany()
                        .HasForeignKey("NewSalaryGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrSalaryDecision", "SalaryDecision")
                        .WithMany("Details")
                        .HasForeignKey("SalaryDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaselineSalaryGrade");

                    b.Navigation("Employee");

                    b.Navigation("NewSalaryGrade");

                    b.Navigation("SalaryDecision");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryGrade", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrSalaryScale", "SalaryScale")
                        .WithMany("Grades")
                        .HasForeignKey("SalaryScaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalaryScale");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryGradeCoefficient", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrSalaryGrade", "SalaryGrade")
                        .WithMany("Coefficients")
                        .HasForeignKey("SalaryGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalaryGrade");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryReviewEmployee", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrSalaryGrade", "CurrentSalaryGrade")
                        .WithMany()
                        .HasForeignKey("CurrentSalaryGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrEmployee", "Employee")
                        .WithMany("ReviewEntries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrSalaryGrade", "ProposedSalaryGrade")
                        .WithMany()
                        .HasForeignKey("ProposedSalaryGradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.Domain.Entities.HrSalaryReviewPeriod", "ReviewPeriod")
                        .WithMany("ReviewEmployees")
                        .HasForeignKey("ReviewPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentSalaryGrade");

                    b.Navigation("Employee");

                    b.Navigation("ProposedSalaryGrade");

                    b.Navigation("ReviewPeriod");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrEmployee", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("DecisionDetails");

                    b.Navigation("ReviewEntries");

                    b.Navigation("Salaries");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrJobTitle", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrOrganizationalUnit", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryDecision", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryGrade", b =>
                {
                    b.Navigation("Coefficients");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryReviewPeriod", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("ReviewEmployees");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryScale", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
