// <auto-generated />
using System;
using HRM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HrmDbContext))]
    [Migration("20260917032243_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRM.Domain.Entities.HrEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("date");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("HrEmployee", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrEmployeeSalary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DecisionId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SalaryGradeId")
                        .HasColumnType("int");

                    b.Property<int>("SalaryScaleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SalaryGradeId");

                    b.HasIndex("SalaryScaleId");

                    b.ToTable("HrEmployeeSalary", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DecisionDate")
                        .HasColumnType("date");

                    b.Property<string>("DecisionNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReviewPeriodId")
                        .HasColumnType("int");

                    b.Property<int?>("SignerEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DecisionNumber")
                        .IsUnique();

                    b.HasIndex("ReviewPeriodId")
                        .IsUnique()
                        .HasDatabaseName("HrSalaryDecision_index_noncancelled_period")
                        .HasFilter("[Status] <> 'CANCELLED'");

                    b.HasIndex("SignerEmployeeId");

                    b.ToTable("HrSalaryDecision", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryDecisionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecisionId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("NewCoefficient")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("NewSalaryGradeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("OldCoefficient")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("OldGradeId")
                        .HasColumnType("int");

                    b.Property<int?>("OldSalaryId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("NewSalaryGradeId");

                    b.HasIndex("OldGradeId");

                    b.HasIndex("OldSalaryId");

                    b.ToTable("HrSalaryDecisionDetail", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int>("GradeNumber")
                        .HasColumnType("int");

                    b.Property<int>("SalaryScaleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SalaryScaleId", "GradeNumber")
                        .IsUnique();

                    b.ToTable("HrSalaryGrade", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryReviewEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentCoefficient")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CurrentGradeId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSalaryId")
                        .HasColumnType("int");

                    b.Property<string>("EligibilityReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EligibilityStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProposedCoefficient")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ProposedGradeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReviewPeriodId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrentGradeId");

                    b.HasIndex("CurrentSalaryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProposedGradeId");

                    b.HasIndex("ReviewPeriodId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("HrSalaryReviewEmployee", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryReviewPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HrSalaryReviewPeriod", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HrSalaryScale", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrEmployeeSalary", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrSalaryDecision", "Decision")
                        .WithMany()
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.Domain.Entities.HrEmployee", "Employee")
                        .WithMany("Salaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrSalaryGrade", "SalaryGrade")
                        .WithMany()
                        .HasForeignKey("SalaryGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrSalaryScale", "SalaryScale")
                        .WithMany("EmployeeSalaries")
                        .HasForeignKey("SalaryScaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Decision");

                    b.Navigation("Employee");

                    b.Navigation("SalaryGrade");

                    b.Navigation("SalaryScale");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryDecision", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrSalaryReviewPeriod", "ReviewPeriod")
                        .WithMany("Decisions")
                        .HasForeignKey("ReviewPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrEmployee", "SignerEmployee")
                        .WithMany()
                        .HasForeignKey("SignerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReviewPeriod");

                    b.Navigation("SignerEmployee");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryDecisionDetail", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrSalaryDecision", "Decision")
                        .WithMany("Details")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrEmployee", "Employee")
                        .WithMany("DecisionDetails")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrSalaryGrade", "NewSalaryGrade")
                        .WithMany()
                        .HasForeignKey("NewSalaryGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrSalaryGrade", "OldGrade")
                        .WithMany()
                        .HasForeignKey("OldGradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.Domain.Entities.HrEmployeeSalary", "OldSalary")
                        .WithMany()
                        .HasForeignKey("OldSalaryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Decision");

                    b.Navigation("Employee");

                    b.Navigation("NewSalaryGrade");

                    b.Navigation("OldGrade");

                    b.Navigation("OldSalary");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryGrade", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrSalaryScale", "SalaryScale")
                        .WithMany("Grades")
                        .HasForeignKey("SalaryScaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalaryScale");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryReviewEmployee", b =>
                {
                    b.HasOne("HRM.Domain.Entities.HrSalaryGrade", "CurrentGrade")
                        .WithMany()
                        .HasForeignKey("CurrentGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrEmployeeSalary", "CurrentSalary")
                        .WithMany()
                        .HasForeignKey("CurrentSalaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrEmployee", "Employee")
                        .WithMany("ReviewEntries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.HrSalaryGrade", "ProposedGrade")
                        .WithMany()
                        .HasForeignKey("ProposedGradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.Domain.Entities.HrSalaryReviewPeriod", "ReviewPeriod")
                        .WithMany("ReviewEmployees")
                        .HasForeignKey("ReviewPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentGrade");

                    b.Navigation("CurrentSalary");

                    b.Navigation("Employee");

                    b.Navigation("ProposedGrade");

                    b.Navigation("ReviewPeriod");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrEmployee", b =>
                {
                    b.Navigation("DecisionDetails");

                    b.Navigation("ReviewEntries");

                    b.Navigation("Salaries");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryDecision", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryReviewPeriod", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("ReviewEmployees");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HrSalaryScale", b =>
                {
                    b.Navigation("EmployeeSalaries");

                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
